package burp.des;

public enum DesAlgorithms {
    DES_CBC_PKCS5Padding,
    DES_CBC_ZeroPadding,
    DES_CBC_NoPadding,
    DES_ECB_PKCS5Padding,
    DES_ECB_ZeroPadding,
    DES_ECB_NoPadding,
    DES_OFB_PKCS5Padding,
    DES_OFB_ZeroPadding,
    DES_OFB_NoPadding,
    DES_CFB_PKCS5Padding,
    DES_CFB_ZeroPadding,
    DES_CFB_NoPadding,
    DESede_CBC_PKCS5Padding,
    DESede_CBC_ZeroPadding,
    DESede_CBC_NoPadding,
    DESede_ECB_PKCS5Padding,
    DESede_ECB_ZeroPadding,
    DESede_ECB_NoPadding,
    DESede_OFB_PKCS5Padding,
    DESede_OFB_ZeroPadding,
    DESede_OFB_NoPadding,
    DESede_CFB_PKCS5Padding,
    DESede_CFB_ZeroPadding,
    DESede_CFB_NoPadding,
    strEnc,
}
